-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "run:uxterm",
    [2] = "run:google-chrome-stable",
    [3] = "run:dropbox",
    [4] = "run:gedit",
    [5] = "run:xcalc",
    [6] = "workspacelayout:",
    [7] = "workspacename:",
    [8] = "run:VirtualBox",
    [9] = "menu.mainmenu:session/exit",
    [10] = "run:netbeans-8.0",
    [11] = "menu.mainmenu:session/restart",
    [12] = "run:lxpanel",
    [13] = "run:gimp",
    [14] = "run:VBoxManage",
    [15] = "run:libreoffice",
    [16] = "run:lxterminal",
    [17] = "run:logout",
}

