-- This file has been generated by notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "run:lxpanel",
    [3] = "run:gimp",
    [4] = "run:google-chrome-stable",
    [5] = "run:VBoxManage",
    [6] = "workspacelayout:",
    [7] = "workspacename:",
    [8] = "run:gedit",
    [9] = "run:libreoffice",
    [10] = "run:lxterminal",
    [11] = "menu.mainmenu:session/exit",
    [12] = "run:logout",
}

