-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1014,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<1>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 66,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 692,
                            ["tl"] = {
                                ["tls"] = 1014,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<2>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 66,
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "horizontal",
                            ["brs"] = 1228,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<2>",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1014,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<1>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 66,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 300,
                            ["x"] = 640,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["hidden"] = true,
            },
        },
    },
}

